# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geocontrolli_rt_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(852, 681)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(852, 681))
        MainWindow.setMaximumSize(QtCore.QSize(852, 681))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("Main/GeoControlli.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.txtbOutMsgs = QtGui.QTextBrowser(self.centralwidget)
        self.txtbOutMsgs.setGeometry(QtCore.QRect(10, 550, 691, 101))
        self.txtbOutMsgs.setObjectName(_fromUtf8("txtbOutMsgs"))
        self.pbExit = QtGui.QPushButton(self.centralwidget)
        self.pbExit.setGeometry(QtCore.QRect(720, 620, 121, 30))
        self.pbExit.setObjectName(_fromUtf8("pbExit"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 831, 531))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabControls = QtGui.QWidget()
        self.tabControls.setObjectName(_fromUtf8("tabControls"))
        self.trwControls = QtGui.QTreeWidget(self.tabControls)
        self.trwControls.setGeometry(QtCore.QRect(7, 69, 391, 431))
        self.trwControls.setRootIsDecorated(True)
        self.trwControls.setHeaderHidden(True)
        self.trwControls.setObjectName(_fromUtf8("trwControls"))
        self.trwControls.headerItem().setText(0, _fromUtf8("1"))
        self.cbContext = QtGui.QComboBox(self.tabControls)
        self.cbContext.setGeometry(QtCore.QRect(610, 100, 201, 30))
        self.cbContext.setObjectName(_fromUtf8("cbContext"))
        self.label_8 = QtGui.QLabel(self.tabControls)
        self.label_8.setGeometry(QtCore.QRect(610, 80, 201, 16))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.pbOpenDbDelivery = QtGui.QPushButton(self.tabControls)
        self.pbOpenDbDelivery.setGeometry(QtCore.QRect(770, 10, 41, 23))
        self.pbOpenDbDelivery.setObjectName(_fromUtf8("pbOpenDbDelivery"))
        self.laDbDelivery = QtGui.QLabel(self.tabControls)
        self.laDbDelivery.setGeometry(QtCore.QRect(10, 12, 131, 16))
        self.laDbDelivery.setObjectName(_fromUtf8("laDbDelivery"))
        self.leDbDelivery = QtGui.QLineEdit(self.tabControls)
        self.leDbDelivery.setGeometry(QtCore.QRect(160, 10, 601, 20))
        self.leDbDelivery.setObjectName(_fromUtf8("leDbDelivery"))
        self.pbSaveChkCtrl = QtGui.QPushButton(self.tabControls)
        self.pbSaveChkCtrl.setEnabled(False)
        self.pbSaveChkCtrl.setGeometry(QtCore.QRect(410, 450, 101, 23))
        self.pbSaveChkCtrl.setObjectName(_fromUtf8("pbSaveChkCtrl"))
        self.pbLoadChkCtrl = QtGui.QPushButton(self.tabControls)
        self.pbLoadChkCtrl.setEnabled(False)
        self.pbLoadChkCtrl.setGeometry(QtCore.QRect(410, 477, 101, 23))
        self.pbLoadChkCtrl.setObjectName(_fromUtf8("pbLoadChkCtrl"))
        self.laDbLog = QtGui.QLabel(self.tabControls)
        self.laDbLog.setGeometry(QtCore.QRect(10, 40, 141, 16))
        self.laDbLog.setObjectName(_fromUtf8("laDbLog"))
        self.leDbLog = QtGui.QLineEdit(self.tabControls)
        self.leDbLog.setGeometry(QtCore.QRect(160, 40, 601, 20))
        self.leDbLog.setObjectName(_fromUtf8("leDbLog"))
        self.pbOpenDbLog = QtGui.QPushButton(self.tabControls)
        self.pbOpenDbLog.setGeometry(QtCore.QRect(770, 40, 41, 23))
        self.pbOpenDbLog.setObjectName(_fromUtf8("pbOpenDbLog"))
        self.pbConnectDb = QtGui.QPushButton(self.tabControls)
        self.pbConnectDb.setEnabled(True)
        self.pbConnectDb.setGeometry(QtCore.QRect(410, 100, 191, 30))
        self.pbConnectDb.setObjectName(_fromUtf8("pbConnectDb"))
        self.label_9 = QtGui.QLabel(self.tabControls)
        self.label_9.setGeometry(QtCore.QRect(410, 80, 191, 16))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gbSessCtrl = QtGui.QGroupBox(self.tabControls)
        self.gbSessCtrl.setGeometry(QtCore.QRect(410, 150, 401, 201))
        self.gbSessCtrl.setAlignment(QtCore.Qt.AlignCenter)
        self.gbSessCtrl.setFlat(False)
        self.gbSessCtrl.setObjectName(_fromUtf8("gbSessCtrl"))
        self.label_2 = QtGui.QLabel(self.gbSessCtrl)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 61, 21))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.leNote = QtGui.QLineEdit(self.gbSessCtrl)
        self.leNote.setGeometry(QtCore.QRect(90, 110, 291, 20))
        self.leNote.setObjectName(_fromUtf8("leNote"))
        self.label_3 = QtGui.QLabel(self.gbSessCtrl)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 61, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.leDelivName = QtGui.QLineEdit(self.gbSessCtrl)
        self.leDelivName.setGeometry(QtCore.QRect(90, 50, 291, 20))
        self.leDelivName.setObjectName(_fromUtf8("leDelivName"))
        self.label = QtGui.QLabel(self.gbSessCtrl)
        self.label.setGeometry(QtCore.QRect(10, 50, 61, 21))
        self.label.setObjectName(_fromUtf8("label"))
        self.leOperator = QtGui.QLineEdit(self.gbSessCtrl)
        self.leOperator.setGeometry(QtCore.QRect(90, 80, 291, 20))
        self.leOperator.setObjectName(_fromUtf8("leOperator"))
        self.pbExecuteControls = QtGui.QPushButton(self.gbSessCtrl)
        self.pbExecuteControls.setEnabled(False)
        self.pbExecuteControls.setGeometry(QtCore.QRect(210, 150, 171, 31))
        self.pbExecuteControls.setMinimumSize(QtCore.QSize(0, 3))
        self.pbExecuteControls.setObjectName(_fromUtf8("pbExecuteControls"))
        self.label_7 = QtGui.QLabel(self.gbSessCtrl)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 251, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.labSqliteVers = QtGui.QLabel(self.tabControls)
        self.labSqliteVers.setEnabled(False)
        self.labSqliteVers.setGeometry(QtCore.QRect(660, 460, 151, 16))
        self.labSqliteVers.setText(_fromUtf8(""))
        self.labSqliteVers.setObjectName(_fromUtf8("labSqliteVers"))
        self.labSpatialiteVers = QtGui.QLabel(self.tabControls)
        self.labSpatialiteVers.setEnabled(False)
        self.labSpatialiteVers.setGeometry(QtCore.QRect(660, 480, 151, 16))
        self.labSpatialiteVers.setText(_fromUtf8(""))
        self.labSpatialiteVers.setObjectName(_fromUtf8("labSpatialiteVers"))
        self.tabWidget.addTab(self.tabControls, _fromUtf8(""))
        self.tabLog = QtGui.QWidget()
        self.tabLog.setObjectName(_fromUtf8("tabLog"))
        self.pbTestSpatial = QtGui.QPushButton(self.tabLog)
        self.pbTestSpatial.setEnabled(False)
        self.pbTestSpatial.setGeometry(QtCore.QRect(130, 470, 110, 23))
        self.pbTestSpatial.setObjectName(_fromUtf8("pbTestSpatial"))
        self.txtbResults = QtGui.QTextBrowser(self.tabLog)
        self.txtbResults.setGeometry(QtCore.QRect(10, 10, 801, 451))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Courier New"))
        self.txtbResults.setFont(font)
        self.txtbResults.setObjectName(_fromUtf8("txtbResults"))
        self.pbEmptyLogBox = QtGui.QPushButton(self.tabLog)
        self.pbEmptyLogBox.setEnabled(True)
        self.pbEmptyLogBox.setGeometry(QtCore.QRect(10, 470, 110, 30))
        self.pbEmptyLogBox.setObjectName(_fromUtf8("pbEmptyLogBox"))
        self.tabWidget.addTab(self.tabLog, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.tbwSessions = QtGui.QTableWidget(self.tab)
        self.tbwSessions.setGeometry(QtCore.QRect(10, 10, 801, 451))
        self.tbwSessions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbwSessions.setWordWrap(False)
        self.tbwSessions.setObjectName(_fromUtf8("tbwSessions"))
        self.tbwSessions.setColumnCount(0)
        self.tbwSessions.setRowCount(0)
        self.tbwSessions.verticalHeader().setVisible(False)
        self.pbReportSessione = QtGui.QPushButton(self.tab)
        self.pbReportSessione.setEnabled(True)
        self.pbReportSessione.setGeometry(QtCore.QRect(360, 470, 131, 30))
        self.pbReportSessione.setObjectName(_fromUtf8("pbReportSessione"))
        self.pbOutTables = QtGui.QPushButton(self.tab)
        self.pbOutTables.setEnabled(True)
        self.pbOutTables.setGeometry(QtCore.QRect(200, 470, 111, 30))
        self.pbOutTables.setObjectName(_fromUtf8("pbOutTables"))
        self.tbvSessions = QtGui.QTableView(self.tab)
        self.tbvSessions.setGeometry(QtCore.QRect(10, 470, 161, 31))
        self.tbvSessions.setLineWidth(1)
        self.tbvSessions.setMidLineWidth(0)
        self.tbvSessions.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tbvSessions.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tbvSessions.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbvSessions.setSortingEnabled(True)
        self.tbvSessions.setWordWrap(False)
        self.tbvSessions.setCornerButtonEnabled(False)
        self.tbvSessions.setObjectName(_fromUtf8("tbvSessions"))
        self.tbvSessions.verticalHeader().setVisible(False)
        self.cbOkResultsOut = QtGui.QCheckBox(self.tab)
        self.cbOkResultsOut.setGeometry(QtCore.QRect(510, 469, 171, 31))
        self.cbOkResultsOut.setObjectName(_fromUtf8("cbOkResultsOut"))
        self.cbDescrizOut = QtGui.QCheckBox(self.tab)
        self.cbDescrizOut.setGeometry(QtCore.QRect(680, 470, 131, 31))
        self.cbDescrizOut.setObjectName(_fromUtf8("cbDescrizOut"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tabDbSelect = QtGui.QWidget()
        self.tabDbSelect.setObjectName(_fromUtf8("tabDbSelect"))
        self.laDbConfig = QtGui.QLabel(self.tabDbSelect)
        self.laDbConfig.setGeometry(QtCore.QRect(30, 40, 121, 16))
        self.laDbConfig.setObjectName(_fromUtf8("laDbConfig"))
        self.pbOpenDbConfig = QtGui.QPushButton(self.tabDbSelect)
        self.pbOpenDbConfig.setGeometry(QtCore.QRect(770, 60, 41, 23))
        self.pbOpenDbConfig.setObjectName(_fromUtf8("pbOpenDbConfig"))
        self.leDbConfig = QtGui.QLineEdit(self.tabDbSelect)
        self.leDbConfig.setGeometry(QtCore.QRect(20, 60, 741, 20))
        self.leDbConfig.setReadOnly(True)
        self.leDbConfig.setObjectName(_fromUtf8("leDbConfig"))
        self.pbCreateEmptyDbLog = QtGui.QPushButton(self.tabDbSelect)
        self.pbCreateEmptyDbLog.setGeometry(QtCore.QRect(20, 430, 181, 23))
        self.pbCreateEmptyDbLog.setObjectName(_fromUtf8("pbCreateEmptyDbLog"))
        self.pbCreateModDoc = QtGui.QPushButton(self.tabDbSelect)
        self.pbCreateModDoc.setGeometry(QtCore.QRect(20, 460, 181, 23))
        self.pbCreateModDoc.setObjectName(_fromUtf8("pbCreateModDoc"))
        self.tabWidget.addTab(self.tabDbSelect, _fromUtf8(""))
        self.pbInfo = QtGui.QPushButton(self.centralwidget)
        self.pbInfo.setGeometry(QtCore.QRect(720, 588, 121, 26))
        self.pbInfo.setObjectName(_fromUtf8("pbInfo"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "GeoControlli_RT", None))
        self.pbExit.setToolTip(_translate("MainWindow", "Esce dal programma", None))
        self.pbExit.setText(_translate("MainWindow", "Esci", None))
        self.label_8.setText(_translate("MainWindow", "Contesto:", None))
        self.pbOpenDbDelivery.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scegliere il database SpatiaLite con i dati geografici da sottoporre a controllo</p></body></html>", None))
        self.pbOpenDbDelivery.setText(_translate("MainWindow", "...", None))
        self.laDbDelivery.setText(_translate("MainWindow", "<html><head/><body><p>DB dati da controllare:</p></body></html>", None))
        self.leDbDelivery.setToolTip(_translate("MainWindow", "<html><head/><body><p>File del database SpatiaLite con i dati geografici da sottoporre a controllo</p></body></html>", None))
        self.pbSaveChkCtrl.setToolTip(_translate("MainWindow", "<html><head/><body><p>Salva l\'insieme delle scelte effettuate sull\'albero dei controlli</p></body></html>", None))
        self.pbSaveChkCtrl.setText(_translate("MainWindow", "Salva scelte...", None))
        self.pbLoadChkCtrl.setToolTip(_translate("MainWindow", "<html><head/><body><p>Carica nell\'albero dei controlli l\'insieme delle scelte salvate</p></body></html>", None))
        self.pbLoadChkCtrl.setText(_translate("MainWindow", "Carica scelte...", None))
        self.laDbLog.setText(_translate("MainWindow", "<html><head/><body><p>DB diagnostica (output):</p></body></html>", None))
        self.leDbLog.setToolTip(_translate("MainWindow", "File del database SpatiaLite per la diagnostica di output", None))
        self.pbOpenDbLog.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scegliere il database SpatiaLite per la diagnostica di output</p></body></html>", None))
        self.pbOpenDbLog.setText(_translate("MainWindow", "...", None))
        self.pbConnectDb.setToolTip(_translate("MainWindow", "<html><head/><body><p>Eseguire le connessioni ai database di configurazione, dati e log</p></body></html>", None))
        self.pbConnectDb.setText(_translate("MainWindow", "Connetti", None))
        self.label_9.setText(_translate("MainWindow", "Connessione ai database", None))
        self.gbSessCtrl.setTitle(_translate("MainWindow", "Sessione di controllo ", None))
        self.label_2.setText(_translate("MainWindow", "Operatore:", None))
        self.leNote.setToolTip(_translate("MainWindow", "<html><head/><body><p>Inserire eventuali note da asscoiare alla sessione di controllo</p></body></html>", None))
        self.label_3.setText(_translate("MainWindow", "Note:", None))
        self.leDelivName.setToolTip(_translate("MainWindow", "Specificare il nome della consegna da associare alla sessione di controllo", None))
        self.label.setText(_translate("MainWindow", "Consegna:", None))
        self.leOperator.setToolTip(_translate("MainWindow", "<html><head/><body><p>Specificare il codice dell\'operatore da asscoiare alla sessione di controllo</p></body></html>", None))
        self.pbExecuteControls.setToolTip(_translate("MainWindow", "<html><head/><body><p>Eseguire la serie dei controlli selezionati</p></body></html>", None))
        self.pbExecuteControls.setText(_translate("MainWindow", "Esegui controlli", None))
        self.label_7.setText(_translate("MainWindow", "Informazioni da associare alla sessione:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabControls), _translate("MainWindow", "Controlli", None))
        self.pbTestSpatial.setToolTip(_translate("MainWindow", "Connect Repository Database", None))
        self.pbTestSpatial.setText(_translate("MainWindow", "Test Spatial Query", None))
        self.pbEmptyLogBox.setToolTip(_translate("MainWindow", "Svuota la lista di log", None))
        self.pbEmptyLogBox.setText(_translate("MainWindow", "Svuota LOG", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLog), _translate("MainWindow", "Log", None))
        self.tbwSessions.setSortingEnabled(True)
        self.pbReportSessione.setToolTip(_translate("MainWindow", "<html><head/><body><p>Crea il report pdf con i risultati dalla sessione di controllo selezionata</p></body></html>", None))
        self.pbReportSessione.setText(_translate("MainWindow", "Crea report sessione", None))
        self.pbOutTables.setToolTip(_translate("MainWindow", "<html><head/><body><p>Crea le tabelle geografiche degli errori risultanti dalla sessione di controllo selezionata</p></body></html>", None))
        self.pbOutTables.setText(_translate("MainWindow", "Crea tabelle out", None))
        self.cbOkResultsOut.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scrive nel report pdf anche i controlli in cui non si sono verificati errori (esito ok)</p></body></html>", None))
        self.cbOkResultsOut.setText(_translate("MainWindow", " Lista completa risultati\n"
"(anche esiti controlli ok)", None))
        self.cbDescrizOut.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scrive nel report pdf la descrizione del tipo di controllo (se diverso dal precedente)</p></body></html>", None))
        self.cbDescrizOut.setText(_translate("MainWindow", " Descrizioni dei\n"
" tipi di controllo", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sessioni", None))
        self.laDbConfig.setText(_translate("MainWindow", "<html><head/><body><p>DB di configurazione:</p></body></html>", None))
        self.pbOpenDbConfig.setToolTip(_translate("MainWindow", "<html><head/><body><p>Scegliere il database SpatiaLite con le configurazioni dei controlli</p></body></html>", None))
        self.pbOpenDbConfig.setText(_translate("MainWindow", "...", None))
        self.leDbConfig.setToolTip(_translate("MainWindow", "Nome del database SpatiaLite con le configurazioni dei controlli", None))
        self.pbCreateEmptyDbLog.setToolTip(_translate("MainWindow", "<html><head/><body><p>Crea un database SpatiaLite vuoto con le impostazioni per essere usato come DB Diagnostico</p><p><br/></p></body></html>", None))
        self.pbCreateEmptyDbLog.setText(_translate("MainWindow", "Crea DB Diagnostico vuoto", None))
        self.pbCreateModDoc.setToolTip(_translate("MainWindow", "<html><head/><body><p>Crea la documentazione dei modelli dei controlli in formato PDF </p></body></html>", None))
        self.pbCreateModDoc.setText(_translate("MainWindow", "Crea PDF documentaz. modelli", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabDbSelect), _translate("MainWindow", "Config", None))
        self.pbInfo.setText(_translate("MainWindow", "Informazioni...", None))

