# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\Users\\utente\\workspace\\GeoControlli_RT\\Main'],
             binaries=[],
             datas=[
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSans-Bold.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSans-BoldItalic.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSans-Italic.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSans-Regular.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSansNarrow-Bold.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSansNarrow-BoldItalic.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSansNarrow-Italic.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LiberationSansNarrow-Regular.ttf','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\mod_geocontrolli_rt.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\mod_spatialite.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\sqlite3.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\geos.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\geos_c.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\iconv.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\LIBEAY32.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libfreexl-1.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libgcc_s_dw2-1.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libgeos-3-5-0.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libgeos_c-1.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libiconv-2.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\liblzma-5.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libproj-9.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libstdc++-6.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\libxml2-2.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\msvcm90.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\MSVCP100.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\msvcp90.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\MSVCR100.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\msvcr90.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\proj.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\python27.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\pywintypes27.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\Qt3Support4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtCore4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtGui4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtNetwork4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtOpenGL4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtSql4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtSvg4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\QtXml4.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\tcl85.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\tk85.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\zlib1.dll','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\geocontrolli_rt_info.bmp','.'),
               ('C:\\Users\\utente\\workspace\\GeoControlli_RT\\altri_file_necessari\\geocontrolli_rt_rc.py','.')
             ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='GeoControlli_RT',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False , icon='GeoControlli.ico')
